//轮播图约束
export class swiperDataModel {
  _id=''
  goods_id=''
  image_src=''
  navigator_url=''
  open_type=''
}
//楼层导航约束
export class NavModel {
  _id=''
  image_src=''
  name=''
  navigator_url=''
  open_type=''
}

//商品数据约束
export class goodsDataModel {
  _id= ""
  add_time= ""
  cat_id= ""
  cat_one_id= ""
  cat_three_id= ""
  cat_two_id= ""
  goods_big_logo= ""
  goods_id= ""
  goods_name= ""
  goods_number= ""
  goods_price= ""
  goods_small_logo= ""
  goods_weight= ""
  hot_mumber= ""
  is_promote= ""
  upd_time= ""
}